export const CINEMATIC_SCENE_TYPES = {
  OPENING_TITLE: 'opening-title',
  WORDMARK_REVEAL: 'wordmark-reveal',
  BRAND_CONTEXT: 'brand-context',
  BRAND_PHILOSOPHY: 'brand-philosophy',
  LOGO_EVOLUTION: 'logo-evolution',
  ICON_DECONSTRUCTION: 'icon-deconstruction',
  LOGO_SYSTEM: 'logo-system',
  TYPOGRAPHY_SYSTEM: 'typography-system',
  COLOR_DIRECTION: 'color-direction',
  APPLICATIONS_SHOWCASE: 'applications-showcase',
  COLLATERAL_SHOWCASE: 'collateral-showcase',
  QUOTE_SCENE: 'quote-scene',
  STATS_SCENE: 'stats-scene',
  FULL_BLEED_MEDIA: 'full-bleed-media',
  GALLERY_SCENE: 'gallery-scene',
  EMBED_SCENE: 'embed-scene',
  CTA_SCENE: 'cta-scene',
  CLOSING_STATEMENT: 'closing-statement',
};

export const CINEMATIC_SHELL_DEFAULTS = {
  progressBar: true,
  sectionIndicator: true,
  keyboardNav: true,
  grainOverlay: true,
  scrollBehavior: 'snap',
};

export const CINEMATIC_ATMOSPHERE_PRESETS = {
  'deep-tech': {
    label: 'Deep Tech',
    floatingAtmosphere: true,
    particles: true,
    orbitalRings: true,
    cursorParallax: true,
    intensity: 'medium',
  },
  'editorial-luxury': {
    label: 'Editorial Luxury',
    floatingAtmosphere: true,
    particles: false,
    orbitalRings: false,
    cursorParallax: true,
    intensity: 'low',
  },
  'cultural-immersive': {
    label: 'Cultural Immersive',
    floatingAtmosphere: true,
    particles: true,
    orbitalRings: true,
    cursorParallax: true,
    intensity: 'high',
  },
  'campaign-electric': {
    label: 'Campaign Electric',
    floatingAtmosphere: true,
    particles: true,
    orbitalRings: false,
    cursorParallax: true,
    intensity: 'high',
  },
  'minimal-glow': {
    label: 'Minimal Glow',
    floatingAtmosphere: true,
    particles: false,
    orbitalRings: false,
    cursorParallax: false,
    intensity: 'low',
  },
};

export const CINEMATIC_SCENE_REGISTRY = {
  [CINEMATIC_SCENE_TYPES.OPENING_TITLE]: {
    label: 'Opening Title',
    family: 'story',
    purpose: 'Create the first emotional hit and establish the world of the brand.',
    requiredProps: ['headline'],
    optionalProps: ['subheadline', 'eyebrow', 'backgroundWord', 'align', 'tone'],
    motionProfile: 'hero-entrance-sequence',
    assetNeeds: [],
    fallback: 'Static centered title lockup.',
    componentName: 'OpeningTitleScene',
  },
  [CINEMATIC_SCENE_TYPES.WORDMARK_REVEAL]: {
    label: 'Wordmark Reveal',
    family: 'identity',
    purpose: 'Introduce the brand mark with controlled theatricality.',
    requiredProps: ['wordmark'],
    optionalProps: ['descriptor', 'logoUrl', 'tagline', 'revealStyle'],
    motionProfile: 'shared-layout-transition',
    assetNeeds: ['logo'],
    fallback: 'Fade-in logo and descriptor.',
    componentName: 'WordmarkRevealScene',
  },
  [CINEMATIC_SCENE_TYPES.BRAND_CONTEXT]: {
    label: 'Brand Context',
    family: 'story',
    purpose: 'Frame the challenge, opportunity, or market context.',
    requiredProps: ['headline', 'body'],
    optionalProps: ['bullets', 'callout', 'beforeState'],
    motionProfile: 'staggered-content-reveal',
    assetNeeds: [],
    fallback: 'Static text plus bullet list.',
    componentName: 'BrandContextScene',
  },
  [CINEMATIC_SCENE_TYPES.BRAND_PHILOSOPHY]: {
    label: 'Brand Philosophy',
    family: 'story',
    purpose: 'Express the emotional and strategic principles of the brand.',
    requiredProps: ['headline', 'principles'],
    optionalProps: ['supportingText'],
    motionProfile: 'title-timeline-reveal',
    assetNeeds: [],
    fallback: 'Stacked principles with minimal transition.',
    componentName: 'BrandPhilosophyScene',
  },
  [CINEMATIC_SCENE_TYPES.LOGO_EVOLUTION]: {
    label: 'Logo Evolution',
    family: 'identity',
    purpose: 'Show before-and-after identity change and explain why it matters.',
    requiredProps: ['before', 'after'],
    optionalProps: ['headline', 'rationale', 'highlights'],
    motionProfile: 'shared-layout-transition',
    assetNeeds: ['logo'],
    fallback: 'Static comparison columns.',
    componentName: 'LogoEvolutionScene',
  },
  [CINEMATIC_SCENE_TYPES.ICON_DECONSTRUCTION]: {
    label: 'Icon Deconstruction',
    family: 'identity',
    purpose: 'Explain the meaning embedded in the symbol.',
    requiredProps: ['headline', 'parts'],
    optionalProps: ['iconUrl', 'notes'],
    motionProfile: 'cursor-follow-glow',
    assetNeeds: ['icon'],
    fallback: 'Annotated icon list.',
    componentName: 'IconDeconstructionScene',
  },
  [CINEMATIC_SCENE_TYPES.LOGO_SYSTEM]: {
    label: 'Logo System',
    family: 'identity',
    purpose: 'Present lockups, usage variants, and application rules.',
    requiredProps: ['headline', 'variants'],
    optionalProps: ['rules', 'logoSet'],
    motionProfile: 'magnetic-cta',
    assetNeeds: ['logo variants'],
    fallback: 'Static variant grid.',
    componentName: 'LogoSystemScene',
  },
  [CINEMATIC_SCENE_TYPES.TYPOGRAPHY_SYSTEM]: {
    label: 'Typography System',
    family: 'system',
    purpose: 'Show hierarchy, voice, and typographic behavior.',
    requiredProps: ['headline', 'fonts'],
    optionalProps: ['samples', 'usageRules'],
    motionProfile: 'headline-shift',
    assetNeeds: [],
    fallback: 'Static specimen layout.',
    componentName: 'TypographySystemScene',
  },
  [CINEMATIC_SCENE_TYPES.COLOR_DIRECTION]: {
    label: 'Color Direction',
    family: 'system',
    purpose: 'Explain palette, roles, and brand mood through color.',
    requiredProps: ['headline', 'palette'],
    optionalProps: ['summary', 'moodWords'],
    motionProfile: 'color-glow',
    assetNeeds: [],
    fallback: 'Palette cards without glow behavior.',
    componentName: 'ColorDirectionScene',
  },
  [CINEMATIC_SCENE_TYPES.APPLICATIONS_SHOWCASE]: {
    label: 'Applications Showcase',
    family: 'proof',
    purpose: 'Show how the identity or campaign appears in the real world.',
    requiredProps: ['headline', 'items'],
    optionalProps: ['supportingText', 'formats'],
    motionProfile: 'multi-panel-scrollytelling',
    assetNeeds: ['mockups', 'images', 'video'],
    fallback: 'Static gallery grid.',
    componentName: 'ApplicationsShowcaseScene',
  },
  [CINEMATIC_SCENE_TYPES.COLLATERAL_SHOWCASE]: {
    label: 'Collateral Showcase',
    family: 'proof',
    purpose: 'Present tactile brand applications like cards, signage, or print.',
    requiredProps: ['headline', 'items'],
    optionalProps: ['detailNotes', 'mockupStyle'],
    motionProfile: 'interactive-object-reveal',
    assetNeeds: ['mockups', 'images'],
    fallback: 'Flat image stack.',
    componentName: 'CollateralShowcaseScene',
  },
  [CINEMATIC_SCENE_TYPES.QUOTE_SCENE]: {
    label: 'Quote Scene',
    family: 'utility',
    purpose: 'Pause the pace and land a key statement or quote.',
    requiredProps: ['headline'],
    optionalProps: ['body', 'attribution'],
    motionProfile: 'editorial-rise',
    assetNeeds: [],
    fallback: 'Static quote block.',
    componentName: 'QuoteScene',
  },
  [CINEMATIC_SCENE_TYPES.STATS_SCENE]: {
    label: 'Stats Scene',
    family: 'utility',
    purpose: 'Present proof points or campaign metrics with visual punch.',
    requiredProps: ['headline', 'items'],
    optionalProps: ['supportingText'],
    motionProfile: 'animated-number-counter',
    assetNeeds: [],
    fallback: 'Static metrics grid.',
    componentName: 'StatsScene',
  },
  [CINEMATIC_SCENE_TYPES.FULL_BLEED_MEDIA]: {
    label: 'Full Bleed Media',
    family: 'utility',
    purpose: 'Create a cinematic pause with large media.',
    requiredProps: ['media'],
    optionalProps: ['headline', 'caption'],
    motionProfile: 'hero-entrance-sequence',
    assetNeeds: ['image or video'],
    fallback: 'Contained media block.',
    componentName: 'FullBleedMediaScene',
  },
  [CINEMATIC_SCENE_TYPES.GALLERY_SCENE]: {
    label: 'Gallery Scene',
    family: 'utility',
    purpose: 'Show several related frames or applications together.',
    requiredProps: ['items'],
    optionalProps: ['headline', 'body'],
    motionProfile: 'editorial-image-stack',
    assetNeeds: ['multiple images'],
    fallback: 'Static image gallery.',
    componentName: 'GalleryScene',
  },
  [CINEMATIC_SCENE_TYPES.EMBED_SCENE]: {
    label: 'Embed Scene',
    family: 'utility',
    purpose: 'Embed a live prototype or external reference in the narrative.',
    requiredProps: ['embedUrl'],
    optionalProps: ['headline', 'body'],
    motionProfile: 'sticky-story-sequence',
    assetNeeds: ['embed url'],
    fallback: 'Linked screenshot card.',
    componentName: 'EmbedScene',
  },
  [CINEMATIC_SCENE_TYPES.CTA_SCENE]: {
    label: 'CTA Scene',
    family: 'utility',
    purpose: 'Ask for approval, feedback, or a next-step decision.',
    requiredProps: ['headline'],
    optionalProps: ['body', 'cta'],
    motionProfile: 'magnetic-cta',
    assetNeeds: [],
    fallback: 'Static call-to-action block.',
    componentName: 'CtaScene',
  },
  [CINEMATIC_SCENE_TYPES.CLOSING_STATEMENT]: {
    label: 'Closing Statement',
    family: 'story',
    purpose: 'End the experience with a confident final statement.',
    requiredProps: ['headline'],
    optionalProps: ['body', 'cta', 'footerNote'],
    motionProfile: 'hero-entrance-sequence',
    assetNeeds: [],
    fallback: 'Static closing lockup.',
    componentName: 'ClosingStatementScene',
  },
};

export const DEFAULT_CINEMATIC_FLOW = {
  mode: 'cinematic-flow',
  cinematicFlow: {
    title: 'Brand Identity Narrative',
    theme: {
      base: '#1A1720',
      text: '#F2F2F2',
      accent: '#1B70A6',
      accentAlt: '#1C7FA6',
      surface: '#373440',
    },
    shell: CINEMATIC_SHELL_DEFAULTS,
    atmosphere: {
      preset: 'deep-tech',
      ...CINEMATIC_ATMOSPHERE_PRESETS['deep-tech'],
    },
    motion: {
      engine: 'motion',
      style: 'cinematic-editorial',
      reducedMotion: true,
      mobileFallback: 'simplified',
    },
    scenes: [
      {
        id: 'opening',
        type: CINEMATIC_SCENE_TYPES.OPENING_TITLE,
        headline: 'Brand Identity',
        subheadline: 'A cinematic walkthrough.',
        layout: 'center-monument',
      },
      {
        id: 'context',
        type: CINEMATIC_SCENE_TYPES.BRAND_CONTEXT,
        headline: 'The opportunity',
        body: 'Frame the challenge, category, and emotional territory.',
      },
      {
        id: 'closing',
        type: CINEMATIC_SCENE_TYPES.CLOSING_STATEMENT,
        headline: 'The system is ready.',
        body: 'Close with clarity and confidence.',
      },
    ],
  },
};

export function getSceneDefinition(type) {
  return CINEMATIC_SCENE_REGISTRY[type] || null;
}

export function listSceneTypes() {
  return Object.keys(CINEMATIC_SCENE_REGISTRY);
}
