const GSAP_PATTERNS = [
  {
        id: 'pinned-hero-reveal',
        label: 'Pinned hero reveal',
        category: 'hero',
        complexity: 'medium',
        impact: 'high',
        bestFor: 'Full-screen hero moments, brand reveal sequences, and immersive opening experiences.',
        useWhen: 'The hero section needs to command attention and establish visual authority before scrolling.',
        avoidWhen: 'The page is content-heavy and users need to reach information quickly.',
        cssOnly: false,
        scrollTrigger: true,
  },
  {
        id: 'timeline-sequence',
        label: 'Timeline sequence',
        category: 'narrative',
        complexity: 'medium',
        impact: 'high',
        bestFor: 'Coordinated multi-element reveals, chapter-based storytelling, and editorial pacing.',
        useWhen: 'Multiple elements need to animate in a precise, choreographed order tied to scroll.',
        avoidWhen: 'Animations are simple fades or single-element transitions that Motion handles well.',
        cssOnly: false,
        scrollTrigger: true,
  },
  {
        id: 'horizontal-scroll-panel',
        label: 'Horizontal scroll panel',
        category: 'section',
        complexity: 'high',
        impact: 'high',
        bestFor: 'Portfolio showcases, product feature walks, and side-scrolling editorial layouts.',
        useWhen: 'Content benefits from a lateral reveal that breaks vertical scroll monotony.',
        avoidWhen: 'The audience expects conventional vertical scrolling or mobile is the primary target.',
        cssOnly: false,
        scrollTrigger: true,
  },
  {
        id: 'parallax-depth-layer',
        label: 'Parallax depth layer',
        category: 'background',
        complexity: 'low',
        impact: 'medium',
        bestFor: 'Adding depth to hero sections, background layering, and subtle environmental motion.',
        useWhen: 'You want to create a sense of depth without heavy 3D rendering.',
        avoidWhen: 'The design is minimal and parallax would feel like unnecessary decoration.',
        cssOnly: false,
        scrollTrigger: true,
  },
  {
        id: 'scrub-progress-animation',
        label: 'Scrub progress animation',
        category: 'navigation',
        complexity: 'low',
        impact: 'medium',
        bestFor: 'Progress indicators, scroll-linked drawing effects, and step-through reveals.',
        useWhen: 'Animation progress should directly map to the user scroll position.',
        avoidWhen: 'The animation should play once on enter rather than scrub with scroll.',
        cssOnly: false,
        scrollTrigger: true,
  },
  {
        id: 'stagger-cascade',
        label: 'Stagger cascade',
        category: 'section',
        complexity: 'low',
        impact: 'medium',
        bestFor: 'Card grids, feature lists, team sections, and any repeating element groups.',
        useWhen: 'A group of similar elements should animate in with rhythmic, cascading timing.',
        avoidWhen: 'There are fewer than three items or the section is already visually busy.',
        cssOnly: false,
        scrollTrigger: true,
  },
  {
        id: 'pinned-chapter-scroll',
        label: 'Pinned chapter scroll',
        category: 'narrative',
        complexity: 'high',
        impact: 'high',
        bestFor: 'Long-form storytelling, proof sections, case study walkthroughs, and title sequences.',
        useWhen: 'Content is structured in chapters and each needs focused screen time while scrolling.',
        avoidWhen: 'The content is short or users need to skim quickly.',
        cssOnly: false,
        scrollTrigger: true,
  },
  {
        id: 'text-split-reveal',
        label: 'Text split reveal',
        category: 'typography',
        complexity: 'medium',
        impact: 'high',
        bestFor: 'Headline reveals, title sequences, and typographic moments that need dramatic entrance.',
        useWhen: 'A key headline or statement deserves a cinematic character or word-level reveal.',
        avoidWhen: 'Body copy or secondary text that should be immediately readable.',
        cssOnly: false,
        scrollTrigger: true,
  },
  ];

function formatGsapKnowledgeBase() {
    const patternsBlock = GSAP_PATTERNS.map((pattern) => (
          [
                  `- ${pattern.id}: ${pattern.label}`,
                  `  category: ${pattern.category}`,
                  `  complexity: ${pattern.complexity}`,
                  `  impact: ${pattern.impact}`,
                  `  bestFor: ${pattern.bestFor}`,
                  `  useWhen: ${pattern.useWhen}`,
                  `  avoidWhen: ${pattern.avoidWhen}`,
                ].join('\n')
        )).join('\n');

  return patternsBlock;
}

module.exports = {
    GSAP_PATTERNS,
    formatGsapKnowledgeBase,
};
