const MOTION_ENGINE_ROLES = {
  motion: {
    label: 'Motion for React',
    role: 'Default React UI animation layer for reveals, hover/tap polish, layout transitions, presence, and lightweight scroll-linked transforms.',
  },
  gsap: {
    label: 'GSAP + ScrollTrigger',
    role: 'Use for cinematic scrollytelling, pinned sections, timeline choreography, title sequences, and tightly art-directed narrative motion.',
  },
  spline: {
    label: 'Spline / Three / WebGL',
    role: 'Use sparingly for signature 3D hero scenes, immersive depth moments, interactive objects, shader atmospheres, and premium hero reveals.',
  },
  lottie: {
    label: 'Lottie',
    role: 'Use for lightweight micro-animations, icon motion, onboarding loops, and compact branded motion assets.',
  },
};

const MOTION_PATTERNS = [
  {
    id: 'hero-entrance-sequence',
    label: 'Hero entrance sequence',
    engine: 'motion',
    category: 'hero',
    complexity: 'low',
    impact: 'high',
    bestFor: 'Premium first impressions, editorial hero blocks, luxury brand reveals',
    useWhen: 'You need an elegant first-load sequence for eyebrow, headline, subhead, and CTA.',
    avoidWhen: 'The page already has heavy background video or 3D motion competing for attention.',
    mobileFallback: 'Reduce stagger distance and duration; keep opacity + slight y motion only.',
    reducedMotion: 'Show content statically with no stagger.',
  },
  {
    id: 'staggered-content-reveal',
    label: 'Staggered content reveal',
    engine: 'motion',
    category: 'section',
    complexity: 'low',
    impact: 'medium',
    bestFor: 'Cards, lists, service pillars, editorial sections',
    useWhen: 'You want the section to feel curated and paced without overwhelming the viewer.',
    avoidWhen: 'There are too many items on screen or content density is already high.',
    mobileFallback: 'Lower offset and stagger timing.',
    reducedMotion: 'Render all items immediately.',
  },
  {
    id: 'magnetic-cta',
    label: 'Magnetic CTA',
    engine: 'motion',
    category: 'interaction',
    complexity: 'medium',
    impact: 'medium',
    bestFor: 'Premium CTA buttons, proposal approval affordances, agency-style polish',
    useWhen: 'You want a tactile, expensive-feeling call to action.',
    avoidWhen: 'The brand is conservative or utility-first.',
    mobileFallback: 'Use press scale only.',
    reducedMotion: 'Static hover color shift.',
  },
  {
    id: 'shared-layout-transition',
    label: 'Shared layout transition',
    engine: 'motion',
    category: 'layout',
    complexity: 'medium',
    impact: 'high',
    bestFor: 'Tabs, editor panes, active indicators, card expansion',
    useWhen: 'UI elements morph or move between states and should feel spatially connected.',
    avoidWhen: 'State changes are too frequent or visually noisy.',
    mobileFallback: 'Keep transform duration short.',
    reducedMotion: 'Swap instantly.',
  },
  {
    id: 'scroll-linked-parallax',
    label: 'Scroll-linked parallax',
    engine: 'motion',
    category: 'scroll',
    complexity: 'medium',
    impact: 'high',
    bestFor: 'Layered editorial depth, product storytelling, premium longform sections',
    useWhen: 'You need depth and atmosphere without full timeline choreography.',
    avoidWhen: 'The page already has pinned sections or heavy 3D scenes.',
    mobileFallback: 'Reduce movement amplitude significantly.',
    reducedMotion: 'Disable parallax entirely.',
  },
  {
    id: 'cursor-follow-glow',
    label: 'Cursor-follow glow',
    engine: 'motion',
    category: 'interaction',
    complexity: 'medium',
    impact: 'medium',
    bestFor: 'Dark premium interfaces, innovation brands, immersive hero wrappers',
    useWhen: 'You want ambient responsiveness around cards or hero surfaces.',
    avoidWhen: 'Accessibility or simplicity is more important than atmosphere.',
    mobileFallback: 'Use static glow or device tilt-free version.',
    reducedMotion: 'Static accent glow.',
  },
  {
    id: 'sticky-story-sequence',
    label: 'Sticky story sequence',
    engine: 'gsap',
    category: 'scroll',
    complexity: 'high',
    impact: 'high',
    bestFor: 'Narrative brand reveals, case study walkthroughs, pitch-deck-like landing experiences',
    useWhen: 'A section should pin while multiple content states play out.',
    avoidWhen: 'The site is short or content does not justify pinning.',
    mobileFallback: 'Convert to stacked sections with simple reveals.',
    reducedMotion: 'Use static section progression.',
  },
  {
    id: 'title-timeline-reveal',
    label: 'Title timeline reveal',
    engine: 'gsap',
    category: 'hero',
    complexity: 'medium',
    impact: 'high',
    bestFor: 'Brand launches, campaign reveals, cinematic landing titles',
    useWhen: 'The brand needs a tightly paced opening with precise sequencing.',
    avoidWhen: 'A quieter or more utilitarian tone is needed.',
    mobileFallback: 'Shorten the sequence and simplify masking.',
    reducedMotion: 'Static hero with minimal fade-in.',
  },
  {
    id: 'multi-panel-scrollytelling',
    label: 'Multi-panel scrollytelling',
    engine: 'gsap',
    category: 'scroll',
    complexity: 'high',
    impact: 'high',
    bestFor: 'Brand story arcs, pitch sections, chaptered narratives',
    useWhen: 'Multiple panels, visuals, or statements need to advance in a single pinned scene.',
    avoidWhen: 'The content can be communicated more clearly in standard sections.',
    mobileFallback: 'Break into normal stacked content.',
    reducedMotion: 'Render all panels as separate sections.',
  },
  {
    id: 'editorial-image-stack',
    label: 'Editorial image stack',
    engine: 'gsap',
    category: 'media',
    complexity: 'medium',
    impact: 'high',
    bestFor: 'Moodboards, gallery reveals, fashion/editorial brand work',
    useWhen: 'Images need cinematic sequence and overlap rather than a plain gallery.',
    avoidWhen: 'The site is content-dense or the media is weak.',
    mobileFallback: 'Use swipeable or stacked cards.',
    reducedMotion: 'Static collage or standard gallery.',
  },
  {
    id: '3d-hero-scene',
    label: '3D hero scene',
    engine: 'spline',
    category: '3d',
    complexity: 'high',
    impact: 'high',
    bestFor: 'Luxury tech, culture launches, product showcases, immersive homepages',
    useWhen: 'A signature visual moment justifies 3D complexity.',
    avoidWhen: 'Budget, performance, or brand tone calls for restraint.',
    mobileFallback: 'Poster image or simplified autoplay-free scene.',
    reducedMotion: 'Static render.',
  },
  {
    id: 'interactive-object-reveal',
    label: 'Interactive object reveal',
    engine: 'spline',
    category: '3d',
    complexity: 'high',
    impact: 'high',
    bestFor: 'Products, artifacts, installations, logo sculptures',
    useWhen: 'The object itself is central to the story and benefits from exploration.',
    avoidWhen: 'There is no meaningful 3D subject.',
    mobileFallback: 'Use pre-rendered image/video loop.',
    reducedMotion: 'Static hero asset.',
  },
  {
    id: 'shader-atmosphere',
    label: 'Shader atmosphere',
    engine: 'spline',
    category: 'background',
    complexity: 'high',
    impact: 'medium',
    bestFor: 'Premium mood, ambient hero backgrounds, innovation brands',
    useWhen: 'You want living depth rather than a flat gradient.',
    avoidWhen: 'Content legibility is at risk.',
    mobileFallback: 'Use static gradient or subtle video.',
    reducedMotion: 'Static background.',
  },
  {
    id: 'lottie-micro-loop',
    label: 'Lottie micro-loop',
    engine: 'lottie',
    category: 'micro',
    complexity: 'low',
    impact: 'medium',
    bestFor: 'Feature callouts, loading states, icon systems, lightweight accent motion',
    useWhen: 'You need compact branded motion without full custom animation code.',
    avoidWhen: 'Large hero moments need more bespoke direction.',
    mobileFallback: 'Play once or show first frame.',
    reducedMotion: 'Static frame.',
  },
  {
    id: 'animated-number-counter',
    label: 'Animated number counter',
    engine: 'motion',
    category: 'data',
    complexity: 'low',
    impact: 'medium',
    bestFor: 'Stats, metrics, pitch proof points',
    useWhen: 'Numbers need a small sense of momentum and clarity.',
    avoidWhen: 'The design is already busy or the values are not important.',
    mobileFallback: 'Shorter duration.',
    reducedMotion: 'Render final value immediately.',
  },
  {
    id: 'section-progress-indicator',
    label: 'Section progress indicator',
    engine: 'motion',
    category: 'navigation',
    complexity: 'low',
    impact: 'medium',
    bestFor: 'Longform experiences, decks, and story-driven portals',
    useWhen: 'The viewer benefits from orientation while scrolling through a narrative.',
    avoidWhen: 'The experience is short and linear.',
    mobileFallback: 'Simplified progress bar.',
    reducedMotion: 'Static progress marker.',
  },
];

function formatMotionKnowledgeBase() {
  const engineBlock = Object.entries(MOTION_ENGINE_ROLES)
    .map(([key, value]) => `- ${key}: ${value.label} — ${value.role}`)
    .join('\n');

  const patternsBlock = MOTION_PATTERNS.map((pattern) => (
    [
      `- ${pattern.id}: ${pattern.label}`,
      `  engine: ${pattern.engine}`,
      `  category: ${pattern.category}`,
      `  complexity: ${pattern.complexity}`,
      `  impact: ${pattern.impact}`,
      `  bestFor: ${pattern.bestFor}`,
      `  useWhen: ${pattern.useWhen}`,
      `  avoidWhen: ${pattern.avoidWhen}`,
      `  mobileFallback: ${pattern.mobileFallback}`,
      `  reducedMotion: ${pattern.reducedMotion}`,
    ].join('\n')
  )).join('\n');

  return {
    engineBlock,
    patternsBlock,
  };
}

module.exports = {
  MOTION_ENGINE_ROLES,
  MOTION_PATTERNS,
  formatMotionKnowledgeBase,
};
